### ISSUE TITLE
using this

### ISSUE THREAD

**Issue by ghost** [KazuCocoa/flutter-appium#1]
It looks liek this will allow me to do remote testing on saucelabs via Appium.
Its in the first paragraph here: https://wiki.saucelabs.com/display/DOCS/Installing+a+Remote+Application+on+a+Real+Device

Can you write a paragraph about how to use this with flutter please :)

**Comment by KazuCocoa** [comment]
Do you mean like the below?
I haven't tried, but I guess you can run on SauceLabs setting the below capability.

```ruby
IOS_OPS = {
  caps: {
    platformName: :ios,
    automationName: 'XCUITest',
    app: 'https://github.com/KazuCocoa/flutter-appium/tree/master/ios/iphonesimulator/Runner.app',
    platformVersion: '10.3',
    deviceName: 'iPhone Simulator',
    useNewWDA: true,
    useJSONSource: true,
  },
  appium_lib: {
    server_url: "https://#{username}:#{access_key}@ondemand.saucelabs.com:443/wd/hub",
    export_session: true,
    wait: 30,
    wait_timeout: 20,
    wait_interval: 1
  }
}.freeze
```

**Comment by KazuCocoa** [comment]
in https://github.com/KazuCocoa/flutter-appium/issues/1#issuecomment-383645035
